### ISSUE TITLE
acme.sh v3.0.0 ZeroSSL.com-CA

### ISSUE THREAD

**Issue by ghost** [markdumay/synology-tls#13]
"Note: From acme.sh v3.0.0, acme.sh is using Zerossl as default ca, you must register the account first(one-time) before you can issue new certs."
https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
https://github.com/acmesh-official/acme.sh/commit/d0b514890a28d13e83bb06efcfb14651e83360c5

Mon Jun 14 11:28:08 UTC 2021] Using CA: https://acme.zerossl.com/v2/DV90
acme_1  | [Mon Jun 14 11:28:08 UTC 2021] No EAB credentials found for ZeroSSL, let's get one
acme_1  | [Mon Jun 14 11:28:08 UTC 2021] acme.sh is using ZeroSSL as default CA now.
acme_1  | [Mon Jun 14 11:28:08 UTC 2021] Please update your account with an email address first.
acme_1  | [Mon Jun 14 11:28:08 UTC 2021] acme.sh --register-account -m my@example.com
acme_1  | [Mon Jun 14 11:28:08 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
acme_1  | [Mon Jun 14 11:28:08 UTC 2021] Please add '--debug' or '--log' to check more details.
acme_1  | [Mon Jun 14 11:28:08 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

**Comment by ghost** [comment]
ZeroSSL has no 90 days wildcard certificates.

https://zerossl.com/pricing/

**Comment by ghost** [comment]
This could be the fix


docker-entrypoint.sh
```
# example
acme.sh  --issue  -d example.com --dns dns_cf    --server  letsencrypt

# old
acme.sh --issue -d '$DOMAIN' -d '*.$DOMAIN' --dns dns_cf $TEST_FLAG $RENEW_FLAG

# untested
acme.sh --issue -d '$DOMAIN' -d '*.$DOMAIN' --dns dns_cf $TEST_FLAG $RENEW_FLAG --server letsencrypt
```
https://github.com/acmesh-official/acme.sh/wiki/Change-default-CA-to-ZeroSSL

**Comment by markdumay** [comment]
Thanks @m4rkv5, I've updated the script and put it in the `develop` branch.

**Comment by ghost** [comment]
I can confirm that a new installation now gets certificates from let's encrypt. 

No ZeroSSL error. I tested production mode and my certificates are correctly installed in Synology DSM.

Auto renew is not tested.

**Comment by markdumay** [comment]
Great, thanks for testing! I pushed the changes to the master branch too, closing this issue. Let me know in case you'd like to reopen it.

**Comment by cirrusflyer** [comment]
> ZeroSSL has no 90 days wildcard certificates.
> 
> https://zerossl.com/pricing/

They do and they're free when using acme.sh.  https://zerossl.com/features/acme/
